### ISSUE TITLE
Region expansion: support solution deployment in Hong Kong, Milan, Cape Town, Bahrain regions

### ISSUE THREAD

**Issue by JoeShi** [awslabs/log-hub#37]
### Describe the feature

The solution cannot be deployed in opt-in regions like Hong Kong, Milan regions. The root cause is that the solution comes with a built-in console which is served via CloudFront. However, CloudFront cannot output logs to S3 buckets in opt-in regions. 

### Use Case

As a customer, I'd like to deploy the solution in Hong Kong, Milan and other opt-in regions. 

### Log Hub version used

v1.1.0

**Comment by YikaiHu** [comment]
Since Cloudfront in AWS OpsIn Region (such as Hong Kong,  Milan, Bahrain) currently does not support the function of logging to the bucket of this region, it is necessary to manually modify the Cloudformation template to deploy Log Hub.

Here is the workaround for Log Hub v1.1.0 to deploy in AWS OpsIn Region.

### Step 1. Download the v1.1.x Log Hub OIDC template.  

- Click: https://aws-gcr-solutions.s3.amazonaws.com/log-hub/v1.1.0/LogHubWithOIDC.template

### Step 2. Delete the `Logging` property in CloudFormation template. 

- Open the template which downloaded in step1.
- Search for `"Logging": {`
- Delete the `Logging` property.
- Save the template. 

![image](https://user-images.githubusercontent.com/34271744/190970126-f9c7988e-c911-43a5-9c5e-83246b96303a.png)


### Step3. Create a CloudFormation Stack by upload edited template
![image](https://user-images.githubusercontent.com/34271744/190970205-b306c3cb-58b6-4acf-88d8-58c939d4bef9.png)
